
# Netlify configuration for single-page applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true # Always serve index.html for any path

# Ensure cache is invalidated for new deployments
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
